default: &default
  adapter: postgresql
  encoding: utf8
  database: example
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  user: <%= ENV['DB_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>

development:
  adapter: postgresql
  encoding: utf8
  database: example
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  user: <%= ENV['DB_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>


production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] || 'example' %>
  host: <%= ENV['RDS_HOSTNAME'] || 'localhost' %>
  port: <%= ENV['RDS_PORT'] || 5432 %>
  user: <%= ENV['RDS_USERNAME'] || 'postgres' %>
  password: <%= ENV['RDS_PASSWORD'] || 'password' %>